config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :comics, only: [:new, :create, :edit, :update]

    root 'dashboard#index'
  end

  resources :comics, only: [:show]

  root 'portals#index'

end

app/models/comic.rb
# == Schema Information
#
# Table name: comics
#
#  id                   :integer          not null, primary key
#  title                :string
#  description          :text
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  series               :string
#  status               :integer          default(0)
#  preview_file_name    :string
#  preview_content_type :string
#  preview_file_size    :integer
#  preview_updated_at   :datetime
#

class Comic < ActiveRecord::Base
  enum status: [:regular, :featured]
  has_many :strips, dependent: :destroy

  has_attached_file :preview, styles: { medium: '300x300>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :preview, content_type: /\Aimage\/.*\Z/

  validates_presence_of :preview
  validates_presence_of :title
  validates_presence_of :series
end

app/models/strip.rb
# == Schema Information
#
# Table name: strips
#
#  id                   :integer          not null, primary key
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  content_file_name    :string
#  content_content_type :string
#  content_file_size    :integer
#  content_updated_at   :datetime
#  comic_id             :integer
#
# Indexes
#
#  index_strips_on_comic_id  (comic_id)
#
# Foreign Keys
#
#  fk_rails_f912f1c14d  (comic_id => comics.id)
#

class Strip < ActiveRecord::Base
  belongs_to :comic

  has_attached_file :content, styles: { medium: '300x300>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :content, content_type: /\Aimage\/.*\Z/

  validates_presence_of :content
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  email              :string           not null
#  encrypted_password :string(128)      not null
#  confirmation_token :string(128)
#  remember_token     :string(128)      not null
#
# Indexes
#
#  index_users_on_email           (email)
#  index_users_on_remember_token  (remember_token)
#

class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/admin/comics_controller.rb
class Admin::ComicsController < ApplicationController
  before_action :require_login

  def new
    @comic = Comic.new
  end

  def create
    @comic = Comic.new(comic_params)

    if @comic.save
      flash[:success] = 'Comic created!'
      redirect_to edit_admin_comic_path(@comic)
    else
      flash.now[:error] = 'Could not save comic'
      render action: :new
    end
  end

  def edit
    @comic = Comic.find(params[:id])
  end

  def update
    @comic = Comic.find(params[:id])

    if @comic.update(comic_params)
      flash[:success] = 'Comic updated!'
      redirect_to edit_admin_comic_path(@comic)
    else
      flash.now[:error] = 'Could not update comic'
      render action: :edit
    end
  end

  private

  def comic_params
    params.require(:comic).permit(:title, :description, :series, :preview)
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :require_login

  def index
    @comics = Comic.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comics_controller.rb
# == Schema Information
#
# Table name: comics
#
#  id                   :integer          not null, primary key
#  title                :string
#  description          :text
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  series               :string
#  status               :integer          default(0)
#  preview_file_name    :string
#  preview_content_type :string
#  preview_file_size    :integer
#  preview_updated_at   :datetime
#

class ComicsController < ApplicationController
  def show
    @comic = Comic.find(params[:id])
  end
end

app/controllers/portals_controller.rb
class PortalsController < ApplicationController
  def index
    @featured_comics = Comic.featured
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/comics/edit.html.erb
<%= form_for [:admin, @comic], html: { multipart: true } do |f| %>
  <% if @comic.errors.any? %>
    <% @comic.errors.full_messages.each do |msg| %>
      <div><%= msg %></div>
    <% end %>
  <% end %>
  <%= f.label :series %>
  <%= f.text_field :series %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= image_tag @comic.preview.url %>
  <%= f.label :preview %>
  <%= f.file_field :preview %>
  <%= f.submit %>
<% end %>

app/views/admin/comics/new.html.erb
<%= form_for [:admin, @comic], html: { multipart: true } do |f| %>
  <% if @comic.errors.any? %>
    <% @comic.errors.full_messages.each do |msg| %>
      <div><%= msg %></div>
    <% end %>
  <% end %>
  <%= f.label :series %>
  <%= f.text_field :series %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :preview %>
  <%= f.file_field :preview %>
  <%= f.submit %>
<% end %>

app/views/admin/dashboard/index.html.erb
<%= link_to 'New Comic', new_admin_comic_path %>
<% @comics.each do |comic| %>
  <div>
    <%= link_to comic.title, edit_admin_comic_path(comic) %>
  </div>
<% end %>

app/views/comics/show.html.erb
<h1><%= @comic.title %></h1>
<p><%= @comic.description %></p>
<% @comic.strips.each do |strip| %>
  <%= image_tag(strip.content.url) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tobangus</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if signed_in? %>
      Signed in as: <%= current_user.email %>
    <%= button_to 'Sign out', sign_out_path, method: :delete %>
  <% else %>
    <%= link_to 'Sign in', sign_in_path %>
  <% end %>

  <div id="flash">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
  </div>

  <%= yield %>

</body>
</html>

app/views/portals/index.html.erb
<% @featured_comics.each do |comic| %>
  <%= link_to image_tag(comic.preview.url), comic_path(comic), class: 'comic-preview' %>
<% end %>